# Generated by Django 3.2.13 on 2022-06-16 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='neighborhood_image',
            field=models.ImageField(blank=True, default='house.jpg', upload_to='neighborhood_image'),
        ),
    ]
